import React, { createContext, useContext, useEffect, useState, useMemo } from 'react';
import type { AppState, Cell, Escalation, ShiftCode, Week, WeekInput, WorkingCopy } from '../types.ts';
import { EMPLOYEES, PREV_SEED, defaultReq, WEEKS_SEED } from '../data/seed.ts';
import { generate } from '../engine/generate.ts';
import { cloneCopy, emptyCopy, cellKey } from '../engine/core.ts';
import { validate } from '../engine/validate.ts';
import { draftNote } from '../engine/note.ts';
import { applyChanges, markAbsent } from '../engine/recommend.ts';

const STORAGE_KEY = 'smart_schedule_app_state_v1';

export interface ToastMessage {
  id: string;
  type: 'success' | 'info' | 'warning' | 'error';
  text: string;
}

interface AppContextValue {
  state: AppState;
  setRole: (role: 'PS' | 'AS') => void;
  toggleTheme: () => void;
  resetState: () => void;
  toasts: ToastMessage[];
  addToast: (text: string, type?: ToastMessage['type']) => void;
  removeToast: (id: string) => void;

  // Actions
  generateWeek: (weekId: string, options?: { keepLocks?: boolean }) => void;
  regenerateWeek: (weekId: string, keepLocks?: boolean) => void;
  updateCell: (weekId: string, empId: string, day: number, value: Cell) => void;
  setDayPk: (weekId: string, day: number, empId: string | null) => void;
  markEmployeeAbsent: (weekId: string, empId: string, days: number[], reason: string) => void;
  applyRecommendation: (weekId: string, changes: { empId: string; day: number; value: Cell }[]) => void;
  setException: (weekId: string, ruleKey: string, reason: string) => void;
  removeException: (weekId: string, ruleKey: string) => void;
  acceptShortage: (weekId: string, slotKey: string, reason: string) => void;
  updateNote: (weekId: string, note: string) => void;
  regenerateNote: (weekId: string) => void;
  submitToAS: (weekId: string) => void;
  withdrawSubmission: (weekId: string) => void;
  approveSchedule: (weekId: string, comment?: string) => void;
  rejectSchedule: (weekId: string, comment: string) => void;

  // Change mode for approved schedules
  startChangeMode: (weekId: string) => void;
  discardChangeMode: (weekId: string) => void;
  submitChangeToAS: (weekId: string) => void;
  approveChange: (weekId: string, comment?: string) => void;
  rejectChange: (weekId: string, comment: string) => void;

  // Escalations
  createEscalation: (weekId: string, day: number, shift: ShiftCode, count: number, message: string) => void;
  resolveEscalation: (escId: string, helperName: string, resolution: string) => void;
  declineEscalation: (escId: string) => void;

  // Roles & Interchangeability
  toggleEmployeeRole: (empId: string) => void;
  setCellDuty: (weekId: string, empId: string, day: number, duty: 'Kasir' | 'Pramuniaga') => void;
  swapEmployeesShift: (weekId: string, emp1Id: string, emp2Id: string, day: number) => void;
  acceptAllExceptionsWithNote: (weekId: string, baseReason?: string) => void;

  // Setup inputs
  updateWeekInput: (weekId: string, input: Partial<WeekInput>) => void;
}

const AppContext = createContext<AppContextValue | null>(null);

function createInitialState(): AppState {
  // Generate approved schedule for week 41
  const w41Roster = generate({
    employees: EMPLOYEES,
    input: { leave: {}, req: defaultReq() },
    prev: PREV_SEED,
    seed: 41,
  });

  const w41Working: WorkingCopy = emptyCopy(w41Roster);
  const w41Week: Week = {
    id: 'w41',
    label: WEEKS_SEED[0].label,
    startISO: WEEKS_SEED[0].startISO,
    input: { leave: {}, req: defaultReq() },
    status: 'approved',
    proposalIndex: 1,
    main: w41Working,
    change: null,
    exceptions: {},
    acceptedShortages: {},
    note: 'Jadwal lengkap dan telah disetujui untuk operasional minggu ini.',
    noteEdited: false,
    validatedAt: Date.now() - 86400000 * 3,
    dirty: false,
    submittedAt: Date.now() - 86400000 * 4,
    lastOutcome: { type: 'approved', at: Date.now() - 86400000 * 3, comment: 'Disetujui. Sesuai kebutuhan toko.' },
    activity: [
      { at: Date.now() - 86400000 * 4, actor: 'Asisten', text: 'Usulan jadwal 1 dibuat' },
      { at: Date.now() - 86400000 * 4, actor: 'PS', text: 'Mengajukan jadwal ke Area Supervisor' },
      { at: Date.now() - 86400000 * 3, actor: 'AS', text: 'Menyetujui jadwal' },
    ],
  };

  // Week 42 starts empty (ready to be generated by the user in Step 1)
  const w42Week: Week = {
    id: 'w42',
    label: WEEKS_SEED[1].label,
    startISO: WEEKS_SEED[1].startISO,
    input: { leave: { dewi: [3, 4] }, req: defaultReq() },
    status: 'empty',
    proposalIndex: 0,
    main: null,
    change: null,
    exceptions: {},
    acceptedShortages: {},
    note: '',
    noteEdited: false,
    validatedAt: null,
    dirty: false,
    submittedAt: null,
    lastOutcome: null,
    activity: [],
  };

  return {
    version: 1,
    role: 'PS',
    employees: EMPLOYEES,
    weekOrder: ['w41', 'w42'],
    weeks: { w41: w41Week, w42: w42Week },
    prevSeed: PREV_SEED,
    escalations: [],
    theme: 'light',
  };
}

export const AppProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [state, setState] = useState<AppState>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.version === 1 && parsed.weeks?.w41 && parsed.weeks?.w42) {
          return parsed;
        }
      }
    } catch (e) {
      console.error('Failed to load state from localStorage', e);
    }
    return createInitialState();
  });

  const [toasts, setToasts] = useState<ToastMessage[]>([]);

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch (e) {
      console.error('Failed to save state to localStorage', e);
    }
  }, [state]);

  const addToast = (text: string, type: ToastMessage['type'] = 'info') => {
    const id = Math.random().toString(36).slice(2, 9);
    setToasts((prev) => [...prev, { id, text, type }]);
    setTimeout(() => {
      removeToast(id);
    }, 4500);
  };

  const removeToast = (id: string) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  };

  const setRole = (role: 'PS' | 'AS') => {
    setState((s) => ({ ...s, role }));
    addToast(`Beralih ke peran ${role === 'PS' ? 'Pimpinan Shift (PS)' : 'Area Supervisor (AS)'}`, 'info');
  };

  const toggleTheme = () => {
    setState((s) => {
      const nextTheme = s.theme === 'light' ? 'dark' : 'light';
      return { ...s, theme: nextTheme };
    });
  };

  const resetState = () => {
    localStorage.removeItem(STORAGE_KEY);
    const initial = createInitialState();
    setState(initial);
    addToast('Data prototipe telah direset ke kondisi awal.', 'info');
  };

  const updateWeekInput = (weekId: string, inputPartial: Partial<WeekInput>) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            input: {
              ...week.input,
              ...inputPartial,
            },
          },
        },
      };
    });
  };

  const getPreviousWeekInfo = (s: AppState, weekId: string) => {
    if (weekId === 'w41') return s.prevSeed;
    // For w42, get previous week w41 info
    const w41 = s.weeks.w41;
    if (w41?.main?.roster) {
      const offs: Record<string, number[]> = {};
      for (const e of s.employees) {
        offs[e.id] = (w41.main.roster.cells[e.id] ?? []).flatMap((c, d) => (c === 'OFF' ? [d] : []));
      }
      return {
        label: w41.label,
        offs,
        sundayPk: w41.main.roster.pk[6] ?? 'andi',
      };
    }
    return s.prevSeed;
  };

  const generateWeek = (weekId: string, options?: { keepLocks?: boolean }) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      const prevInfo = getPreviousWeekInfo(s, weekId);

      const fixed: Record<string, Cell> = {};
      if (options?.keepLocks && week.main) {
        for (const k of Object.keys(week.main.manual)) {
          const [id, d] = k.split('|');
          fixed[k] = week.main.roster.cells[id]?.[Number(d)];
        }
      }

      const seedNumber = 42 + week.proposalIndex;
      const roster = generate({
        employees: s.employees,
        input: week.input,
        prev: prevInfo,
        seed: seedNumber,
        fixed,
      });

      const copy: WorkingCopy = {
        roster,
        absences: week.main?.absences ?? {},
        absenceReasons: week.main?.absenceReasons ?? {},
        manual: options?.keepLocks ? { ...week.main?.manual } : {},
      };

      const issues = validate({
        employees: s.employees,
        input: week.input,
        prev: prevInfo,
        copy,
        exceptions: week.exceptions,
        acceptedShortages: week.acceptedShortages,
        escalations: s.escalations.filter((x) => x.weekId === weekId),
      });

      const note = week.noteEdited ? week.note : draftNote(s.employees, week.input, copy, issues);

      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            status: 'draft',
            proposalIndex: week.proposalIndex + 1,
            main: copy,
            note,
            dirty: false,
            validatedAt: Date.now(),
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'Asisten',
                text: `Usulan jadwal #${week.proposalIndex + 1} berhasil disusun`,
              },
            ],
          },
        },
      };
    });
    addToast('✦ Jadwal berhasil disusun oleh Asisten!', 'success');
  };

  const regenerateWeek = (weekId: string, keepLocks = false) => {
    generateWeek(weekId, { keepLocks });
  };

  const updateCell = (weekId: string, empId: string, day: number, value: Cell) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      const isChange = week.status === 'approved' || week.status === 'change_pending';
      const target = isChange ? week.change : week.main;
      if (!target) return s;

      const nextCopy = cloneCopy(target);
      nextCopy.roster.cells[empId][day] = value;
      nextCopy.manual[cellKey(empId, day)] = true;

      const prevInfo = getPreviousWeekInfo(s, weekId);
      const issues = validate({
        employees: s.employees,
        input: week.input,
        prev: prevInfo,
        copy: nextCopy,
        exceptions: week.exceptions,
        acceptedShortages: week.acceptedShortages,
        escalations: s.escalations.filter((x) => x.weekId === weekId),
      });

      const note = week.noteEdited ? week.note : draftNote(s.employees, week.input, nextCopy, issues);

      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            [isChange ? 'change' : 'main']: nextCopy,
            dirty: true,
            note,
            validatedAt: Date.now(),
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'PS',
                text: `Mengubah jadwal ${s.employees.find((e) => e.id === empId)?.name ?? empId} menjadi ${value ?? 'Kosong'}`,
              },
            ],
          },
        },
      };
    });
  };

  const setDayPk = (weekId: string, day: number, empId: string | null) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      const isChange = week.status === 'approved' || week.status === 'change_pending';
      const target = isChange ? week.change : week.main;
      if (!target) return s;

      const nextCopy = cloneCopy(target);
      nextCopy.roster.pk[day] = empId;

      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            [isChange ? 'change' : 'main']: nextCopy,
            dirty: true,
            validatedAt: Date.now(),
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'PS',
                text: `Menetapkan ${empId ? s.employees.find((e) => e.id === empId)?.name : 'tidak ada'} sebagai PK hari ke-${day + 1}`,
              },
            ],
          },
        },
      };
    });
    addToast('Penetapan PK berhasil diperbarui', 'info');
  };

  const markEmployeeAbsent = (weekId: string, empId: string, days: number[], reason: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      const isChange = week.status === 'approved' || week.status === 'change_pending';
      const target = isChange ? week.change : week.main;
      if (!target) return s;

      const prevInfo = getPreviousWeekInfo(s, weekId);
      const ctx = {
        employees: s.employees,
        input: week.input,
        prev: prevInfo,
        copy: target,
        exceptions: week.exceptions,
        acceptedShortages: week.acceptedShortages,
        escalations: s.escalations.filter((x) => x.weekId === weekId),
      };

      const { copy: updatedCopy, pkNotes } = markAbsent(ctx, empId, days, reason);

      const issues = validate({
        ...ctx,
        copy: updatedCopy,
      });

      const note = draftNote(s.employees, week.input, updatedCopy, issues);
      const emp = s.employees.find((e) => e.id === empId);

      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            [isChange ? 'change' : 'main']: updatedCopy,
            dirty: true,
            note,
            validatedAt: Date.now(),
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'PS',
                text: `Menandai ${emp?.name} tidak hadir (${reason})`,
              },
              ...pkNotes.map((pn) => ({
                at: Date.now(),
                actor: 'Asisten' as const,
                text: pn,
              })),
            ],
          },
        },
      };
    });
    addToast('Ketidakhadiran berhasil ditandai & dampak dihitung ulang', 'warning');
  };

  const applyRecommendation = (weekId: string, changes: { empId: string; day: number; value: Cell }[]) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      const isChange = week.status === 'approved' || week.status === 'change_pending';
      const target = isChange ? week.change : week.main;
      if (!target) return s;

      const prevInfo = getPreviousWeekInfo(s, weekId);
      const ctx = {
        employees: s.employees,
        input: week.input,
        prev: prevInfo,
        copy: target,
        exceptions: week.exceptions,
        acceptedShortages: week.acceptedShortages,
        escalations: s.escalations.filter((x) => x.weekId === weekId),
      };

      const { copy: updatedCopy, pkNotes } = applyChanges(ctx, target, changes, true);
      const issues = validate({
        ...ctx,
        copy: updatedCopy,
      });

      const note = draftNote(s.employees, week.input, updatedCopy, issues);

      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            [isChange ? 'change' : 'main']: updatedCopy,
            dirty: true,
            note,
            validatedAt: Date.now(),
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'PS',
                text: 'Menerapkan rekomendasi pengganti dari Asisten',
              },
              ...pkNotes.map((pn) => ({
                at: Date.now(),
                actor: 'Asisten' as const,
                text: pn,
              })),
            ],
          },
        },
      };
    });
    addToast('✦ Rekomendasi pengganti berhasil diterapkan!', 'success');
  };

  const setException = (weekId: string, ruleKey: string, reason: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      const exceptions = { ...week.exceptions, [ruleKey]: reason };
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            exceptions,
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'PS',
                text: `Menerima pengecualian: ${reason}`,
              },
            ],
          },
        },
      };
    });
    addToast('Pengecualian disimpan dengan alasan operasional', 'info');
  };

  const removeException = (weekId: string, ruleKey: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      const exceptions = { ...week.exceptions };
      delete exceptions[ruleKey];
      return {
        ...s,
        weeks: { ...s.weeks, [weekId]: { ...week, exceptions } },
      };
    });
  };

  const acceptShortage = (weekId: string, slotKey: string, reason: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            acceptedShortages: {
              ...week.acceptedShortages,
              [slotKey]: reason,
            },
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'PS',
                text: `Menerima kekurangan staf (${slotKey}): ${reason}`,
              },
            ],
          },
        },
      };
    });
    addToast('Kekurangan staf diterima sebagai catatan operasional', 'warning');
  };

  const updateNote = (weekId: string, note: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: { ...week, note, noteEdited: true },
        },
      };
    });
  };

  const regenerateNote = (weekId: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week || !week.main) return s;
      const prevInfo = getPreviousWeekInfo(s, weekId);
      const issues = validate({
        employees: s.employees,
        input: week.input,
        prev: prevInfo,
        copy: week.main,
        exceptions: week.exceptions,
        acceptedShortages: week.acceptedShortages,
        escalations: s.escalations.filter((x) => x.weekId === weekId),
      });
      const note = draftNote(s.employees, week.input, week.main, issues);
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: { ...week, note, noteEdited: false },
        },
      };
    });
    addToast('Catatan operasional disusun ulang secara otomatis', 'info');
  };

  const submitToAS = (weekId: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            status: 'pending',
            submittedAt: Date.now(),
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'PS',
                text: 'Mengajukan jadwal ke Area Supervisor untuk ditinjau',
              },
            ],
          },
        },
      };
    });
    addToast('Jadwal berhasil dikirim ke Area Supervisor!', 'success');
  };

  const withdrawSubmission = (weekId: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            status: 'draft',
            lastOutcome: { type: 'withdrawn', at: Date.now() },
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'PS',
                text: 'Menarik kembali pengajuan jadwal (kembali ke Draf)',
              },
            ],
          },
        },
      };
    });
    addToast('Pengajuan ditarik kembali. Jadwal tetap tersimpan dalam status Draf.', 'info');
  };

  const approveSchedule = (weekId: string, comment?: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            status: 'approved',
            lastOutcome: { type: 'approved', comment, at: Date.now() },
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'AS',
                text: `Menyetujui jadwal${comment ? `: "${comment}"` : ''}`,
              },
            ],
          },
        },
      };
    });
    addToast('✓ Jadwal disetujui oleh Area Supervisor!', 'success');
  };

  const rejectSchedule = (weekId: string, comment: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            status: 'draft',
            lastOutcome: { type: 'rejected', comment, at: Date.now() },
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'AS',
                text: `Menolak jadwal: "${comment}"`,
              },
            ],
          },
        },
      };
    });
    addToast('✕ Jadwal ditolak. Jadwal kembali ke Draf untuk diperbaiki oleh PS.', 'warning');
  };

  const startChangeMode = (weekId: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week || !week.main) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            change: cloneCopy(week.main),
          },
        },
      };
    });
  };

  const discardChangeMode = (weekId: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            change: null,
          },
        },
      };
    });
    addToast('Perubahan dibatalkan. Kembali ke jadwal yang disetujui.', 'info');
  };

  const submitChangeToAS = (weekId: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week || !week.change) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            status: 'change_pending',
            submittedAt: Date.now(),
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'PS',
                text: 'Mengajukan perubahan jadwal ke Area Supervisor',
              },
            ],
          },
        },
      };
    });
    addToast('Perubahan jadwal berhasil dikirim ke Area Supervisor!', 'success');
  };

  const approveChange = (weekId: string, comment?: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week || !week.change) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            status: 'approved',
            main: week.change,
            change: null,
            lastOutcome: { type: 'change_approved', comment, at: Date.now() },
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'AS',
                text: `Menyetujui perubahan jadwal${comment ? `: "${comment}"` : ''}`,
              },
            ],
          },
        },
      };
    });
    addToast('✓ Perubahan jadwal disetujui oleh Area Supervisor!', 'success');
  };

  const rejectChange = (weekId: string, comment: string) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            status: 'approved',
            change: null,
            lastOutcome: { type: 'change_rejected', comment, at: Date.now() },
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'AS',
                text: `Menolak perubahan jadwal: "${comment}". Jadwal sebelumnya dipertahankan.`,
              },
            ],
          },
        },
      };
    });
    addToast('✕ Perubahan jadwal ditolak. Versi disetujui sebelumnya tetap berlaku.', 'info');
  };

  const createEscalation = (weekId: string, day: number, shift: ShiftCode, count: number, message: string) => {
    const escId = 'esc_' + Math.random().toString(36).slice(2, 8);
    const newEsc: Escalation = {
      id: escId,
      weekId,
      day,
      shift,
      count,
      message,
      status: 'pending',
      createdAt: Date.now(),
    };
    setState((s) => {
      const week = s.weeks[weekId];
      return {
        ...s,
        escalations: [...s.escalations, newEsc],
        weeks: week
          ? {
              ...s.weeks,
              [weekId]: {
                ...week,
                activity: [
                  ...week.activity,
                  {
                    at: Date.now(),
                    actor: 'PS',
                    text: `Mengajukan bantuan lintas toko untuk hari ke-${day + 1} Shift ${shift}`,
                  },
                ],
              },
            }
          : s.weeks,
      };
    });
    addToast('Permintaan bantuan lintas toko berhasil dieskalasi ke AS', 'info');
  };

  const resolveEscalation = (escId: string, helperName: string, resolution: string) => {
    setState((s) => {
      const esc = s.escalations.find((e) => e.id === escId);
      if (!esc) return s;
      const updatedEsc: Escalation = {
        ...esc,
        status: 'resolved',
        helperName,
        resolution,
        resolvedAt: Date.now(),
      };
      const week = s.weeks[esc.weekId];
      return {
        ...s,
        escalations: s.escalations.map((e) => (e.id === escId ? updatedEsc : e)),
        weeks: week
          ? {
              ...s.weeks,
              [esc.weekId]: {
                ...week,
                activity: [
                  ...week.activity,
                  {
                    at: Date.now(),
                    actor: 'AS',
                    text: `Menyelesaikan bantuan lintas toko: ${helperName} (${resolution})`,
                  },
                ],
              },
            }
          : s.weeks,
      };
    });
    addToast('Permintaan bantuan lintas toko diselesaikan oleh AS', 'success');
  };

  const declineEscalation = (escId: string) => {
    setState((s) => ({
      ...s,
      escalations: s.escalations.map((e) => (e.id === escId ? { ...e, status: 'declined', resolvedAt: Date.now() } : e)),
    }));
    addToast('Permintaan bantuan lintas toko ditolak oleh AS', 'warning');
  };

  const toggleEmployeeRole = (empId: string) => {
    setState((s) => {
      const emp = s.employees.find((e) => e.id === empId);
      if (!emp) return s;
      if (emp.position === 'CIF' || emp.position === 'SSL') {
        return s;
      }
      const nextRole = emp.position === 'Kasir' ? 'Pramuniaga' : 'Kasir';
      const updatedEmployees = s.employees.map((e) => (e.id === empId ? { ...e, position: nextRole as any } : e));
      return {
        ...s,
        employees: updatedEmployees,
      };
    });
    addToast('Peran karyawan berhasil diubah (Kasir ⇄ Pramuniaga)', 'info');
  };

  const setCellDuty = (weekId: string, empId: string, day: number, duty: 'Kasir' | 'Pramuniaga') => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      const isChange = week.status === 'approved' || week.status === 'change_pending';
      const target = isChange ? week.change : week.main;
      if (!target) return s;

      const nextCopy = cloneCopy(target);
      if (!nextCopy.duties) nextCopy.duties = {};
      nextCopy.duties[cellKey(empId, day)] = duty;

      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            [isChange ? 'change' : 'main']: nextCopy,
          },
        },
      };
    });
    addToast(`Tugas shift ditetapkan sebagai: ${duty}`, 'info');
  };

  const swapEmployeesShift = (weekId: string, emp1Id: string, emp2Id: string, day: number) => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week) return s;
      const isChange = week.status === 'approved' || week.status === 'change_pending';
      const target = isChange ? week.change : week.main;
      if (!target) return s;

      const nextCopy = cloneCopy(target);
      const val1 = nextCopy.roster.cells[emp1Id][day];
      const val2 = nextCopy.roster.cells[emp2Id][day];

      nextCopy.roster.cells[emp1Id][day] = val2;
      nextCopy.roster.cells[emp2Id][day] = val1;
      nextCopy.manual[cellKey(emp1Id, day)] = true;
      nextCopy.manual[cellKey(emp2Id, day)] = true;

      const prevInfo = getPreviousWeekInfo(s, weekId);
      const issues = validate({
        employees: s.employees,
        input: week.input,
        prev: prevInfo,
        copy: nextCopy,
        exceptions: week.exceptions,
        acceptedShortages: week.acceptedShortages,
        escalations: s.escalations.filter((x) => x.weekId === weekId),
      });

      const note = draftNote(s.employees, week.input, nextCopy, issues);
      const name1 = s.employees.find((e) => e.id === emp1Id)?.name.split(' ')[0] ?? emp1Id;
      const name2 = s.employees.find((e) => e.id === emp2Id)?.name.split(' ')[0] ?? emp2Id;

      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            [isChange ? 'change' : 'main']: nextCopy,
            dirty: true,
            note,
            validatedAt: Date.now(),
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'PS',
                text: `Menukar jadwal ${name1} (${val1 ?? 'Kosong'}) dengan ${name2} (${val2 ?? 'Kosong'}) pada hari ke-${day + 1}`,
              },
            ],
          },
        },
      };
    });
    addToast('✦ Penukaran jadwal berhasil dilakukan!', 'success');
  };

  const acceptAllExceptionsWithNote = (weekId: string, baseReason = 'Penyesuaian kebutuhan operasional toko oleh Pimpinan Shift') => {
    setState((s) => {
      const week = s.weeks[weekId];
      if (!week || !week.main) return s;
      const prevInfo = getPreviousWeekInfo(s, weekId);
      const issues = validate({
        employees: s.employees,
        input: week.input,
        prev: prevInfo,
        copy: week.main,
        exceptions: week.exceptions,
        acceptedShortages: week.acceptedShortages,
        escalations: s.escalations.filter((x) => x.weekId === weekId),
      });

      const nextExceptions = { ...week.exceptions };
      const nextShortages = { ...week.acceptedShortages };

      for (const i of issues) {
        if (i.severity === 'error') {
          nextExceptions[i.key] = baseReason;
        } else if (i.severity === 'shortage' && !i.resolution) {
          nextShortages[`${i.day}|${i.shift}`] = baseReason;
        }
      }

      const updatedIssues = validate({
        employees: s.employees,
        input: week.input,
        prev: prevInfo,
        copy: week.main,
        exceptions: nextExceptions,
        acceptedShortages: nextShortages,
        escalations: s.escalations.filter((x) => x.weekId === weekId),
      });

      const note = draftNote(s.employees, week.input, week.main, updatedIssues);

      return {
        ...s,
        weeks: {
          ...s.weeks,
          [weekId]: {
            ...week,
            exceptions: nextExceptions,
            acceptedShortages: nextShortages,
            note,
            activity: [
              ...week.activity,
              {
                at: Date.now(),
                actor: 'PS',
                text: 'Menyetujui semua penyesuaian sebagai catatan pengecualian untuk AS',
              },
            ],
          },
        },
      };
    });
    addToast('Semua catatan aturan dimasukkan ke catatan AS & siap dikirim!', 'success');
  };

  const value = useMemo(
    () => ({
      state,
      setRole,
      toggleTheme,
      resetState,
      toasts,
      addToast,
      removeToast,
      generateWeek,
      regenerateWeek,
      updateCell,
      setDayPk,
      markEmployeeAbsent,
      applyRecommendation,
      setException,
      removeException,
      acceptShortage,
      updateNote,
      regenerateNote,
      submitToAS,
      withdrawSubmission,
      approveSchedule,
      rejectSchedule,
      startChangeMode,
      discardChangeMode,
      submitChangeToAS,
      approveChange,
      rejectChange,
      createEscalation,
      resolveEscalation,
      declineEscalation,
      toggleEmployeeRole,
      setCellDuty,
      swapEmployeesShift,
      acceptAllExceptionsWithNote,
      updateWeekInput,
    }),
    [state, toasts],
  );

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
};

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) throw new Error('useApp must be used within AppProvider');
  return context;
};
